name: Integration Test

on:
  push:
    branches: [ main, vibe ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build -t check-smart .

    - name: Create virtual disk
      run: |
        # Install required packages
        sudo apt-get update
        sudo apt-get install -y qemu-utils qemu-system-x86 smartmontools

        # Create a virtual disk
        qemu-img create -f raw /tmp/disk.img 1G

        # Start QEMU with the virtual disk
        sudo qemu-system-x86_64 -enable-kvm -m 256 \
          -drive file=/tmp/disk.img,format=raw,if=ide \
          -nographic -daemonize

        # Wait for device to appear
        sleep 5

        # Find the device name (usually /dev/sdb or similar)
        DEVICE=$(lsblk -d -o NAME,TYPE | grep disk | tail -n1 | cut -d' ' -f1)
        echo "DEVICE=/dev/$DEVICE" >> $GITHUB_ENV

        # Enable SMART on the device
        sudo smartctl -s on /dev/$DEVICE

    - name: Run basic tests
      run: |
        # Test help output
        docker run check-smart /usr/lib/nagios/plugins/check_smart.pl --help

        # Test version output
        docker run check-smart /usr/lib/nagios/plugins/check_smart.pl -v

        # Test with real device
        docker run --device=/dev/${{ env.DEVICE }} check-smart /usr/lib/nagios/plugins/check_smart.pl -d /dev/${{ env.DEVICE }} -i auto

    - name: Cleanup
      if: always()
      run: |
        # Kill QEMU
        sudo pkill qemu-system-x86
        rm -f /tmp/disk.img
