# @file launchhelp.yml
---
name: Launch help

# Trigger the workflow on push or pull request
on: [push, pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install perl
      run: |
        sudo apt-get install -qq -yy perl
    - name: Launch script with --help
      run: |
        ./check_smart.pl --help
